// ── Audit event types ─────────────────────────────────────────────────────────
// Audit events are immutable append-only records. No update, no delete.

export const AUTH_AUDIT_EVENT_TYPES = [
  // Authentication
  'LOGIN',
  'LOGIN_FAILED',
  'LOGOUT',
  'SESSION_EXPIRED',
  'TOKEN_REFRESH',
  'TOKEN_REFRESH_FAILED',
  'PASSWORD_CHANGED',
  'ACCOUNT_LOCKED',
  'ACCOUNT_UNLOCKED',
  // Authorization
  'ACCESS_GRANTED',
  'ACCESS_DENIED',
  // Role & permission management
  'ROLE_ASSIGNED',
  'ROLE_REVOKED',
  'PERMISSION_GRANTED',
  'PERMISSION_REVOKED',
  // Delegation
  'DELEGATION_CREATED',
  'DELEGATION_USED',
  'DELEGATION_REVOKED',
  'DELEGATION_EXPIRED',
  // Hierarchy
  'HIERARCHY_ASSIGNED',
  'HIERARCHY_REVOKED',
  // Policy
  'POLICY_APPLIED',
  'POLICY_OVERRIDDEN',
] as const
export type AuthAuditEventType = typeof AUTH_AUDIT_EVENT_TYPES[number]

export const AUDIT_OUTCOMES = ['SUCCESS', 'FAILURE', 'PARTIAL'] as const
export type AuditOutcome = typeof AUDIT_OUTCOMES[number]

// ── AuthAuditEvent ────────────────────────────────────────────────────────────
// No updatedAt — audit events are sealed at creation.

export interface AuthAuditEvent {
  readonly id: string
  readonly eventType: AuthAuditEventType
  readonly userId: string               // acting user (may be system account)
  readonly targetUserId?: string        // subject of the operation (e.g. user being assigned a role)
  readonly sessionId?: string
  readonly resource?: string
  readonly action?: string
  readonly outcome: AuditOutcome
  readonly reason?: string
  readonly delegationId?: string        // set when action was performed under delegation
  readonly policyId?: string            // set when a policy was the deciding factor
  readonly ipAddress?: string
  readonly userAgent?: string
  readonly metadata: Readonly<Record<string, string>>
  readonly occurredAt: string           // ISO 8601 — when the event happened (may differ from createdAt)
  readonly createdAt: string            // ISO 8601 — when the record was persisted
}

// ── IAuditEventRepository — append-only ───────────────────────────────────────

export interface IAuditEventRepository {
  /** Append a new audit event. id and createdAt are generated by the repo. */
  append(event: Omit<AuthAuditEvent, 'id' | 'createdAt'>): Promise<AuthAuditEvent>
  findById(id: string): Promise<AuthAuditEvent | null>
  findByUserId(userId: string, limit?: number): Promise<readonly AuthAuditEvent[]>
  findBySessionId(sessionId: string): Promise<readonly AuthAuditEvent[]>
  findByEventType(type: AuthAuditEventType, limit?: number): Promise<readonly AuthAuditEvent[]>
  findByTimeRange(from: string, to: string, limit?: number): Promise<readonly AuthAuditEvent[]>
  findByTargetUser(targetUserId: string, limit?: number): Promise<readonly AuthAuditEvent[]>
  count(): Promise<number>
}
